name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install black flake8 pytest
      - name: Lint and format
        run: |
          black --check src tests
          flake8 src tests
      - name: Run tests
        run: |
          pytest -q
